BRAWN = ('brawn', 'Brawn', 'Br')
AGILITY = ('agility', 'Agility', 'Ag')
INTELLECT = ('intellect', 'Intellect', 'int')
CUNNING = ('cunning', 'Cunning', 'Cun')
WILLPOWER = ('willpower', 'Willpower', 'Will')
PRESENCE = ('presence', 'Presence', 'Pr')
